// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGO3-M21O5Tyv99hD8ZbwxjkAGiqI0rg',
    appId: '1:716490420262:web:3256be596e747799f136e7',
    messagingSenderId: '716490420262',
    projectId: 'freddit-54177',
    authDomain: 'freddit-54177.firebaseapp.com',
    storageBucket: 'freddit-54177.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw7zBLgVmXCLs7dfeJqm6wsIqTYvsWA7Y',
    appId: '1:716490420262:android:37b51f0a079357d3f136e7',
    messagingSenderId: '716490420262',
    projectId: 'freddit-54177',
    storageBucket: 'freddit-54177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Mu-ZU2tjBQkiGTV3dH62tF2BhPwopp0',
    appId: '1:716490420262:ios:1c492e3df514336ef136e7',
    messagingSenderId: '716490420262',
    projectId: 'freddit-54177',
    storageBucket: 'freddit-54177.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
